### ISSUE TITLE
Github updater?

### ISSUE THREAD

**Issue by jonathan-dejong** [khromov/acf-local-json-manager#3]
Yo! 

Keep using this plugin and love it more and more :) 
Was thinking.. perhaps you should add it to Wordpress.org OR include the github updater so we can benefit from updates you do to it?

**Comment by khromov** [comment]
I've added GitHub Updater support in version 1.2, see 4073c8e30e3fd0d3b252a3a40ee3af61a0b6a109

Since this plugin requires changes to your own code to be useful, I'm not sure it would be a great fit for WP.org (which [has recently banned framework plugins](https://wptavern.com/the-wordpress-plugin-directory-will-no-longer-accept-frameworks))

PS.
It's also possible to add it via Composer, like this:

`composer.json`

```
...
"repositories": [
  { "type": "vcs", "url": "git@github.com:khromov/acf-local-json-manager.git" }
}
...
"require": {
  "khromov/acf-local-json-manager": "~1.0"
}
...
```

**Comment by jonathan-dejong** [comment]
Great! Sorry I didn't check before :) 

Yeah I know about composer, use it for other github repos. For us it wont be useful for the majority of our projects tho as we have a lot of smaller ones as well where we can just use the themes json.
